export const DRAGGE_INGREDIENT = 'DRAGGE_INGREDIENT';
export const DELETE_INGREDIENT = 'DELETE_INGREDIENT';
export const DRAGGE_BUN = 'DRAGGE_BUN';

export const GIVE_UNIQUE_ID = 'GIVE_UNIQUE_ID';

export const GET_TOTAL_PRICE = 'GET_TOTAL_PRICE';

export const CLEAR_COSTRUCTOR = 'CLEAR_COSTRUCTOR';

export const REORDER_CONSTRUCTOR = 'REORDER_CONSTRUCTOR';

export const INCREASE_BUN = 'INCREASE_BUN';